import { Field, InputType } from '@nestjs/graphql';

@InputType()
export class EmployeeCreateDTO {
    // id not necessary as its generated by db 
  @Field()
  first_name: string;

  @Field()
  last_name: string;

  @Field({ nullable: true })
  city: string;
}
